// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSl50vG-PBvUtFfS5l_dYOylsxEMkpz0',
    appId: '1:537966992545:web:d4ecccb781b29d6b5fa4e0',
    messagingSenderId: '537966992545',
    projectId: 'shuttleaide-testing',
    authDomain: 'shuttleaide-testing.firebaseapp.com',
    databaseURL: 'https://shuttleaide-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttleaide-testing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUT0TEiqZ1GwNx2vjDCqUwKc2kJ6CzdGU',
    appId: '1:537966992545:android:586c0991517fb9b35fa4e0',
    messagingSenderId: '537966992545',
    projectId: 'shuttleaide-testing',
    databaseURL: 'https://shuttleaide-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttleaide-testing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYtlTTFqbn1dtmEfJoYNgftK_Wa2bEwx8',
    appId: '1:537966992545:ios:47d0966beafbce765fa4e0',
    messagingSenderId: '537966992545',
    projectId: 'shuttleaide-testing',
    databaseURL: 'https://shuttleaide-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttleaide-testing.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYtlTTFqbn1dtmEfJoYNgftK_Wa2bEwx8',
    appId: '1:537966992545:ios:47d0966beafbce765fa4e0',
    messagingSenderId: '537966992545',
    projectId: 'shuttleaide-testing',
    databaseURL: 'https://shuttleaide-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttleaide-testing.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJSl50vG-PBvUtFfS5l_dYOylsxEMkpz0',
    appId: '1:537966992545:web:26323868a8aeade95fa4e0',
    messagingSenderId: '537966992545',
    projectId: 'shuttleaide-testing',
    authDomain: 'shuttleaide-testing.firebaseapp.com',
    databaseURL: 'https://shuttleaide-testing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttleaide-testing.firebasestorage.app',
  );
}
